# Generated by Django 4.1.2 on 2022-10-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SeoulBusInfo',
            fields=[
                ('bus_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('bus_type', models.CharField(max_length=1)),
                ('update_time', models.CharField(max_length=14)),
                ('bus_number', models.CharField(max_length=128)),
                ('gpsX', models.CharField(max_length=32)),
                ('gpsY', models.CharField(max_length=32)),
                ('congestion', models.CharField(max_length=1)),
                ('isRunning', models.CharField(max_length=1)),
                ('isFull', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SeoulRouteInfo',
            fields=[
                ('route_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('route_type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('start_stop', models.CharField(max_length=128)),
                ('end_stop', models.CharField(max_length=128)),
                ('first_time', models.CharField(max_length=14)),
                ('last_time', models.CharField(max_length=14)),
                ('length', models.CharField(max_length=10)),
                ('interval', models.CharField(max_length=10)),
            ],
        ),
    ]
