# Generated by Django 4.1.2 on 2022-10-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityinfo',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
