# Generated by Django 4.1.2 on 2022-10-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_cityinfo_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seoulrouteinfo',
            old_name='end_stop',
            new_name='first_stop',
        ),
        migrations.RenameField(
            model_name='seoulrouteinfo',
            old_name='name',
            new_name='last_stop',
        ),
        migrations.RenameField(
            model_name='seoulrouteinfo',
            old_name='first_time',
            new_name='time_first',
        ),
        migrations.RenameField(
            model_name='seoulrouteinfo',
            old_name='last_time',
            new_name='time_last',
        ),
        migrations.RemoveField(
            model_name='seoulrouteinfo',
            name='start_stop',
        ),
        migrations.AlterField(
            model_name='seoulrouteinfo',
            name='route_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
