# Generated by Django 4.1.2 on 2022-10-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_end_stop_seoulrouteinfo_first_stop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoulrouteinfo',
            name='route_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
