# Generated by Django 4.1.2 on 2022-10-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_seoulrouteinfo_route_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoulrouteinfo',
            name='interval',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seoulrouteinfo',
            name='length',
            field=models.FloatField(),
        ),
    ]
