# Generated by Django 4.1.2 on 2022-10-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_seoulrouteinfo_interval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seoulbusinfo',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='seoulbusinfo',
            name='bus_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
