# Generated by Django 4.1.2 on 2022-10-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_seoulbusinfo_update_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoulbusinfo',
            name='route_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
