# Generated by Django 4.1.2 on 2022-10-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_seoulbusinfo_route_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoulbusinfo',
            name='update_time',
            field=models.DateField(auto_now=True),
        ),
    ]
