# Generated by Django 4.1.2 on 2022-11-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_seoulbusinfo_update_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusanBusInfo',
            fields=[
                ('carno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lineno', models.CharField(max_length=10)),
                ('bstopnm', models.CharField(max_length=50)),
                ('lowplate', models.IntegerField()),
                ('gpsym', models.CharField(max_length=10)),
                ('lin', models.CharField(max_length=10)),
                ('lat', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BusanRouteInfo',
            fields=[
                ('lineid', models.IntegerField(primary_key=True, serialize=False)),
                ('buslinenum', models.CharField(max_length=30)),
                ('busType', models.CharField(max_length=20)),
                ('companyid', models.CharField(max_length=70)),
                ('startpoint', models.CharField(max_length=40)),
                ('endpoint', models.CharField(max_length=40)),
                ('firsttime', models.CharField(max_length=30)),
                ('endtime', models.CharField(max_length=30)),
                ('headway', models.CharField(max_length=10)),
            ],
        ),
    ]
