# Generated by Django 4.1.2 on 2022-11-01 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_busanbusinfo_busanrouteinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busanrouteinfo',
            old_name='busType',
            new_name='bustype',
        ),
    ]
