# Generated by Django 4.1.2 on 2022-11-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_rename_bustype_busanrouteinfo_bustype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busanrouteinfo',
            name='lineid',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
