# Generated by Django 4.1.2 on 2022-11-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_busanrouteinfo_lineid'),
    ]

    operations = [
        migrations.AddField(
            model_name='busanbusinfo',
            name='isRunning',
            field=models.CharField(default='Y', max_length=1),
            preserve_default=False,
        ),
    ]
