# Generated by Django 4.1.2 on 2022-11-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_busanbusinfo_isrunning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busanbusinfo',
            name='isRunning',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='seoulbusinfo',
            name='isFull',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='seoulbusinfo',
            name='isRunning',
            field=models.CharField(max_length=3),
        ),
    ]
