# Generated by Django 4.1.2 on 2022-11-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_alter_busanbusinfo_lowplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busanbusinfo',
            name='lowplate',
            field=models.CharField(max_length=4),
        ),
    ]
