# Generated by Django 4.1.2 on 2022-11-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_busanbusinfo_lowplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationBusInfo',
            fields=[
                ('routenm', models.CharField(max_length=30)),
                ('vehicleno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('routetp', models.CharField(max_length=10)),
                ('nodenm', models.CharField(max_length=30)),
                ('gpslati', models.CharField(max_length=20)),
                ('gpslong', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NationRoute',
            fields=[
                ('routeid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('citycode', models.CharField(max_length=5)),
                ('routeno', models.CharField(max_length=30)),
                ('routetp', models.CharField(max_length=10)),
                ('endnodenm', models.CharField(max_length=30)),
                ('startnodenm', models.CharField(max_length=30)),
                ('endvehicletime', models.CharField(max_length=4)),
                ('startvehicletime', models.CharField(max_length=4)),
            ],
        ),
    ]
