# Generated by Django 4.1.2 on 2022-11-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_nationbusinfo_nationroute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NationRoute',
            new_name='NationRouteInfo',
        ),
    ]
