# Generated by Django 4.1.2 on 2022-11-02 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_rename_nationroute_nationrouteinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationrouteinfo',
            name='citycode',
        ),
        migrations.AddField(
            model_name='nationrouteinfo',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.cityinfo'),
            preserve_default=False,
        ),
    ]
