# Generated by Django 4.1.2 on 2022-11-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_remove_nationrouteinfo_citycode_nationrouteinfo_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationbusinfo',
            name='isRunning',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
