# Generated by Django 4.1.2 on 2022-11-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_nationbusinfo_isrunning'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationbusinfo',
            name='routeid',
            field=models.IntegerField(default='0'),
        ),
    ]
