# Generated by Django 4.1.2 on 2022-11-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_alter_nationbusinfo_routeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationbusinfo',
            name='routeid',
            field=models.CharField(max_length=30),
        ),
    ]
